---
Name: goldfinch-component-brands
---
Goldfinch\Component\Brands\Admin\BrandsAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\BlocksAdminExtension

Goldfinch\Component\Brands\Blocks\BrandsBlock:
  extensions:
    - Goldfinch\Helpers\Extensions\BaseElementExtension

Goldfinch\Component\Brands\Models\BrandItem:
  extensions:
    - Goldfinch\Helpers\Extensions\DataObjectSluggable
    - Goldfinch\Helpers\Extensions\SummaryFieldExtension

Goldfinch\Component\Brands\Models\BrandCategory:
  extensions:
    - Goldfinch\Helpers\Extensions\DataObjectSluggable

---
Name: goldfinch-component-brands-icon
Only:
  moduleexists: "goldfinch/enchantment"
---
Goldfinch\Component\Brands\Admin\BrandsAdmin:
  menu_icon_class: "bi-google-play"

Goldfinch\Component\Brands\Blocks\BrandsBlock:
  icon: "bi-google-play"
